name: 🚀 Deploy Natours

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📁 Setup Folder
        run: |
          rm -rf ~/natours
          mkdir -p ~/natours
          cp -r * ~/natours/

      - name: 📦 Install
        run: |
          cd ~/natours/natours/FinalSection
          npm install

      - name: 🔄 Restart App
        run: |
          cd ~/natours/natours/FinalSection
          pm2 delete natours || true
          pm2 start server.js --name natours
          pm2 save
