name: 🚀 Direct Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # 🔥 THIS IS KEY

    steps:
      - name: 📥 Pull latest code
        run: |
          cd ~/natours || git clone https://github.com/HitikVachheta07/Natoursproject.git ~/natours
          cd ~/natours
          cd ~/FinalSection
          git pull origin main

      - name: 📦 Install dependencies
        run: |
          cd ~/natours
          cd ~/FinalSection
          npm install

      - name: 🔄 Restart server
        run: |
          pm2 stop natours || true
          pm2 start server.js --name natours
          pm2 save

      - name: ✅ Done
        run: echo "Deployment successful 🚀"
